package com.gearreald.tullframe;
import net.tullco.tullutils.FileUtils;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class TullFrame {
	
	public TullFrame(){
		
	}
}
